"""Tools for the validation of the simulator and custom sensors."""

from ._camval import plot_cam_vs_measured
from ._preproc import (
    PreprocResult,
    align_ccycles_corr,
    build_ccycle_matrix,
    build_chpoints_table,
    build_fcr_array,
    correct_baseline_wander,
    correct_longterm_baseline_wander,
    match_nominal_signal,
    match_sampling,
    plot_combined_measurement,
    plot_signal_slices,
    plot_stacked_ccycles,
    plot_stacked_slices,
    preproc_for_validation,
    split_cam_rotations_corr,
    split_combined_measurement,
    t_cam_rotation,
)
from ._stats import (
    ArrayComparator,
    CrossCompareResult,
    SignalComparator,
    a2s_comp,
    cross_compare,
    nrmse,
    nrmse_s,
    pearson,
    pearson_s,
    plot_observed_values,
    rmse,
    rmse_s,
    with_crop,
    with_resampling,
)

__all__ = [
    e.__name__  # type: ignore[attr-defined]
    for e in [
        plot_cam_vs_measured,
        PreprocResult,
        align_ccycles_corr,
        build_ccycle_matrix,
        build_chpoints_table,
        build_fcr_array,
        correct_baseline_wander,
        correct_longterm_baseline_wander,
        match_nominal_signal,
        match_sampling,
        plot_combined_measurement,
        plot_signal_slices,
        plot_stacked_ccycles,
        plot_stacked_slices,
        preproc_for_validation,
        split_cam_rotations_corr,
        split_combined_measurement,
        t_cam_rotation,
        ArrayComparator,
        CrossCompareResult,
        SignalComparator,
        a2s_comp,
        cross_compare,
        nrmse,
        nrmse_s,
        pearson,
        pearson_s,
        plot_observed_values,
        rmse,
        rmse_s,
        with_crop,
        with_resampling,
    ]
]
